### ISSUE TITLE
use a yaml file to maintain the different software packages

### ISSUE THREAD

**Issue by birkb** [batchworksde/iksdp_desktop#36]
Move all package definitions into such a yaml structure.
```yaml
packages:
  debian:
    enabled: true
    app:
      chromium:
       name: chromium
       enabled: true
  github:
    enabled: true
    app:
      rustdesk:
        name: rustdesk
        enabled: true
  vendor:
    enabled: true
    app:
      zoom:
        name: zoom
        enabled: true
  flatpak:
    enabled: true
    flathub:
      enabled: true
      app:
        shortwave:
          name: de.haeckerfelix.Shortwave
          enabled: true
        flameshot:
          name: org.flameshot.Flameshot
          enabled: true
       
```
The goal is to keep everything in one place, avoid having to constantly modify the code and to be able to easily enable/disable packages or complete sources.
